[sel BGM_SEL top]
[s]Persona[e]
[s]Shin Megami Tensei[e]
[s]SMT Spin Off[e]
[s]Pick for me[e]
[s]Stop the music[e]
[s]Cancel[e]

[msg HUKA_ORDER_BGM_CHANGE [Fuuka]]
[s]Sure![n][w][e]
[s]...Here are the series I have.[n]Which one do you want to hear?[n][w][e]

[msg HUKA_ORDER_BGM_CHANGE_SE [Fuuka]]
[s]Sure![n][w][e]
[s]...Here is what I have.[n]Which one do you want to hear?[n][w][e]

[msg TitleName]
[s]MP3 Player[w][e]


[sel BGM_SEL_PS top]
[s]Persona 5 Royal[e]
[s]Persona 4 Golden[e]
[s]Persona 3 Reload[e]
[s]Persona 3 FES[e]
[s]Next Page[e]
[s]Pick for me[e]

[sel BGM_SEL_PS_2 top]
[s]Persona 1 (PS1)[e]
[s]Persona 1 (PSP)[e]
[s]Persona 2: Innocent Sin[e]
[s]Persona 2: Eternal Punishment[e]
[s]Next Page[e]
[s]Previous Page[e]
[s]Pick for me[e]

[sel BGM_SEL_PS_3 top]
[s]Persona Q[e]
[s]Persona Q2[e]
[s]Persona 5 Strikers[e]
[s]Previous Page[e]
[s]Pick for me[e]

[sel BGM_SEL_SMT top]
[s]SMT V[e]
[s]SMT IV/A[e]
[s]SMT III Nocturne[e]
[s]SMT II[e]
[s]SMT I[e]
[s]Pick for me[e]
[s]Back[e]

[sel BGM_SEL_SMT_SO top]
[s]Soul Hackers 2[e]
[s]Soul Hackers[e]
[s]Digital Devil Saga 1&2[e]
[s]Fire Emblem Encore[e]
[s]Devil Survivor[e]
[s]Devil Summoner[e]
[s]Pick for me[e]
[s]Back[e]



[sel BGM_SEL_P5R top]
[s]King, Queen, and Slave[e] 
[s]King, Queen, and Slave -Another Version-[e] 
[s]A Woman[e]
[s]A Woman -Another Version-[e] 

[sel BGM_SEL_P5R_1 top]
[s]Price[e] 
[s]Price -Another Version-[e] 
[s]When Mother was There[e] 
[s]When Mother was There -Another Version-[e]

[sel BGM_SEL_P5R_2 top]
[s]Sweatshop[e] 
[s]Sweatshop -Another Version-[e] 
[s]The Whims of Fate[e] 
[s]Ark[e] 

[sel BGM_SEL_P5R_3 top]
[s]Freedom and Security[e] 
[s]Gentle Madman[e]
[s]Out of Kindness[e] 
[s]Mementos[e] 

[sel BGM_SEL_P5R_4 top]
[s]Mementos -Lower Layer-[e] 
[s]Mementos -Middle Layer-[e] 
[s]Mementos -Upper Layer-[e] 
[s]Mementos -New Layer-[e] 



[sel BGM_SEL_P4G top]
[s]Castle[e]
[s]Sauna[e]
[s]Theater[e]
[s]Game[e]

[sel BGM_SEL_P4G_2 top]
[s]Secret Base[e]
[s]Heaven[e]
[s]Long Way[e]
[s]Corridor[e]

[sel BGM_SEL_P4G_3 top]
[s]Memory[e]



[sel BGM_SEL_P3R top]
[s]Thebel (Block 1)[e]
[s]Arqa (Block 2)[e]
[s]Yabbashah (Block 3)[e]
[s]Tziah (Block 4)[e]

[sel BGM_SEL_P3R_2 top]
[s]Harabah (Block 5)[e]
[s]Adamah (Block 6)[e]


[sel BGM_SEL_Q1 top]
[s]You in Wonderland[e]
[s]Sweets and Cards[e]
[s]Shadow in Wonderland[e]
[s]Group Date Cafe[e]

[sel BGM_SEL_Q1_2 top]
[s]Longing and Instinct[e]
[s]Evil Spirits Club[e]
[s]Before the Silence[e]
[s]Inaba Pride Exhibit[e]

[sel BGM_SEL_Q1_3 top]
[s]Looming Danger[e]
[s]Footsteps of Time[e]



[sel BGM_SEL_Q2 top]
[s]Welcome to Kamo City[e]
[s]Blind City[e]
[s]Blind City -another version-[e]
[s]Paradise and Survival[e]

[sel BGM_SEL_Q2_2 top]
[s]Jungle Quest[e]
[s]Jungle Quest -another version-[e]
[s]Synchronized City[e]
[s]Synchronized City -another version-[e]

[sel BGM_SEL_Q2_3 top]
[s]Connected[e]
[s]Robot Lab[e]
[s]Amuzing World[e]
[s]Obscure World[e]

[sel BGM_SEL_Q2_4 top]
[s]Peculiar World -another version-[e]
[s]Peculiar World[e]
[s]Last Scene[e]

[sel BGM_SEL_P3F top]
[s]Malebolge (Block 1)[e]
[s]Cocytus (Block 2)[e]
[s]Caina (Block 3)[e]
[s]Antenora (Block 4)[e]

[sel BGM_SEL_P3F_2 top]
[s]Ptolomea (Block 5)[e]
[s]Judecca (Block 6)[e]
[s]Empyrean (Block 7)[e]


[sel BGM_SEL_P1PS1 top]
[s]Hospital (After Disaster)[e]
[s]City 1 Post Disaster[e]
[s]Dungeon - Police Station[e]
[s]Dungeon - Abandoned Factory Underground Passage[e]

[sel BGM_SEL_P1PS1_2 top]
[s]City 2[e]
[s]Dungeon - SEBEC Above Ground[e]
[s]Dungeon - SEBEC Underground Research Lab[e]
[s]City 2 Accident[e]

[sel BGM_SEL_P1PS1_3 top]
[s]Dungeon - Nemesis Tower[e]
[s]Dungeon - Kama Palace[e]
[s]Dungeon - House[e]
[s]Dungeon - Deva-Yuga[e]

[sel BGM_SEL_P1PS1_4 top]
[s]Thanatos Tower[e]
[s]Dungeon - Pandora's Den (Deepmost Area)[e]
[s]Dungeon - Ruins[e]
[s]Consciousness[e]

[sel BGM_SEL_P1PS1_5 top]
[s]Hypnos Tower[e]

[sel BGM_SEL_P1PSP top]
[s]Mad Hospital[e]
[s]Let Butterflies Spread Until the Dawn[e]
[s]Mikage Police Station[e]
[s]SEBEC[e]

[sel BGM_SEL_P1PSP_2 top]
[s]Kama Palace[e]
[s]Lost Forest[e]
[s]Mana Castle[e]
[s]Haunted Mansion[e]

[sel BGM_SEL_P1PSP_3 top]
[s]Deva-Yuga[e]
[s]Alaya Cavern[e]
[s]Avidya World[e]
[s]Ice Castle[e]

[sel BGM_SEL_P1PSP_4 top]
[s]Hypnos Tower[e]
[s]Nemesis Tower[e]
[s]Thanatos Tower[e]
[s]Devils Peak[e]

[sel BGM_SEL_P1PSP_5 top]
[s]Mikage Ruins[e]

[sel BGM_SEL_P2EP top]
[s]Seven Sisters High School[e]
[s]Mt Katatsumuri[e]
[s]Morimoto Hospital[e]
[s]GOLD[e]

[sel BGM_SEL_P2EP_2 top]
[s]Club Zodiac[e]
[s]Aoba Park[e]
[s]Science Laboratory[e]
[s]Sumaru TV[e]

[sel BGM_SEL_P2EP_3 top]
[s]Smile Hirasaka[e]
[s]Abandoned Factory[e]
[s]Nichirinmaru[e]
[s]Undersea Ruins[e]

[sel BGM_SEL_P2EP_4 top]
[s]Mt Iwato[e]
[s]Subway Construction Site[e]
[s]Ameno Torifune[e]
[s]Sumaru Castle[e]

[sel BGM_SEL_P2EP_5 top]
[s]Monado Mandala[e]
[s]Kasugayama High School[e]
[s]Giga Macho[e]
[s]Kadath Mandala[e]

[sel BGM_SEL_P2IS top]
[s]Seven Sisters High School B[e]
[s]Zodiac[e]
[s]Kasugayama High School[e]
[s]Bomb Shelter[e]

[sel BGM_SEL_P2IS_2 top]
[s]Mu Continent[e]
[s]Giga Macho[e]
[s]Aoba Park[e]
[s]Concert Hall[e]

[sel BGM_SEL_P2IS_3 top]
[s]Smile Hirasaka[e]
[s]GOLD[e]
[s]Mt Iwato[e]
[s]Mt Katatsumuri[e]

[sel BGM_SEL_P2IS_4 top]
[s]Caracol[e]
[s]Aquarius Shrine[e]
[s]Scorpio Shrine[e]
[s]Taurus Shrine[e]

[sel BGM_SEL_P2IS_5 top]
[s]Leo Shrine[e]
[s]Milky Way[e]
[s]Xibalba[e]
[s]Abandoned Factory[e]


[sel BGM_SEL_P5S top]
[s]Devil's Castle[e]
[s]Loving Wonderland[e]
[s]Voracious Waltz[e]
[s]Singularity[e]

[sel BGM_SEL_P5S_2 top]
[s]Counterfeit Phantom[e]
[s]Anti HERO[e]
[s]Jail in Abyss[e]
[s]Tower of Life[e]










































[sel BGM_SEL_SMTV top]
[s]Takanawa[e]
[s]Tamachi[e]
[s]West Shinbashi[e]
[s]Tokyo Diet Building[e]

[sel BGM_SEL_SMTV_3 top]
[s]Tennozu[e]
[s]Konan[e]
[s]Shinagawa Station[e]
[s]Ginza[e]

[sel BGM_SEL_SMTV_4 top]
[s]Kanda Myoujin[e]
[s]Tokyo Station[e]
[s]Odaiba[e]
[s]Ueno[e]

[sel BGM_SEL_SMTV_5 top]
[s]Fairy Village[e]
[s]Demon King's Castle[e]
[s]Temple of Eternity[e]
[s]The Empyrean[e]

[sel BGM_SEL_SMTV_6 top]
[s]Jouin High School[e]



[sel BGM_SEL_DDS top]
[s]Amaravati[e]
[s]Human Hunting[e]
[s]Road to Sodom[e]
[s]Road to Sodom -Second-[e]

[sel BGM_SEL_DDS_2 top]
[s]Meeeeaaaat! Processing Plant[e]
[s]Prisoner's Nightmare[e]
[s]Tower of Reunion[e]
[s]Egg of the Universe[e]

[sel BGM_SEL_DDS_3 top]
[s]Five Years Before[e]
[s]Rest in Peace, My Friend[e]
[s]One Way Stairs[e]
[s]Nirvana[e]

[sel BGM_SEL_DDS_4 top]
[s]Muladhara[e]
[s]Svadhisthana[e]
[s]Sahasrara[e]
[s]Manipura[e]

[sel BGM_SEL_DDS_5 top]
[s]Anahata[e]
[s]Point 136[e]
[s]Ajna[e]



[sel BGM_SEL_DS top]
[s]Dungeon 1[e]
[s]Dungeon 2[e]
[s]Dungeon 3[e]
[s]Dungeon 4[e]

[sel BGM_SEL_DS_2 top]
[s]Dungeon 5[e]
[s]Astral World[e]
[s]Ancient Tomb[e]




[sel BGM_SEL_FE top]
[s]Illusory Shibuya[e]
[s]Illusory Urahara[e]
[s]Illusory Daitou TV[e]
[s]Illusory Daiba Studio[e]

[sel BGM_SEL_FE_2 top]
[s]Illusory Area of Memories[e]
[s]Illusory Dolhr[e]

[sel BGM_SEL_SH top]
[s]Sea Arc 11F[e]
[s]Sea Arc[e]
[s]Algon Headquarters[e]
[s]Futagamikado Basement[e]

[sel BGM_SEL_SH_2 top]
[s]Akane Mall[e]
[s]Amami Airport (Reality)[e]
[s]Amami Airport (Vision Quest)[e]
[s]Astronomy Museum[e]

[sel BGM_SEL_SH_3 top]
[s]Algon NS Building[e]



[sel BGM_SEL_SMT4 top]
[s]Tokyo[e]
[s]Aboveground Urban Area A[e]
[s]Challenge Quest B[e]
[s]Blasted Tokyo[e]

[sel BGM_SEL_SMT4_2 top]
[s]Infernal Tokyo[e]
[s]Ueno Underground District[e]
[s]Aboveground Urban Area B[e]
[s]Aquila Statue Plaza[e]

[sel BGM_SEL_SMT4_3 top]
[s]Members Only Club[e]
[s]Challenge Quest A[e]
[s]Lucifer's Palace[e]
[s]Naraku Upper Strata[e]

[sel BGM_SEL_SMT4_4 top]
[s]Shinjuku Underground District[e]
[s]Aboveground Urban Area C[e]
[s]Camp Ichigaya[e]
[s]Ikebukuro Underground District[e]

[sel BGM_SEL_SMT4_5 top]
[s]Naraku Lower Strata[e]
[s]Domain[e]
[s]Roppongi Area[e]
[s]Shibuya Underground District[e]

[sel BGM_SEL_SMT4_6 top]
[s]Pluto Castle[e]
[s]Tsuloko Hongwanji[e]
[s]Infernal Kasumigaseki[e]
[s]Infernal Tokyo[e]

[sel BGM_SEL_SMT4_7 top]
[s]Infernal Tokyo Underground District[e]
[s]Traffic[e]
[s]Infernal Ichigaya[e]



[sel BGM_SEL_SMT4A top]
[s]East Madness[e]
[s]Time of Decision[e]
[s]Kinshi Park[e]
[s]Outer Universe[e]

[sel BGM_SEL_SMT4A_2 top]
[s]Large Map[e]
[s]Fairy Forest[e]
[s]TD15 kgsk[e]



[sel BGM_SEL_SMT9 top]
[s]Shinjuku[e]
[s]Kichijouji 1[e]
[s]Kichijouji 2[e]
[s]Harajuku[e]

[sel BGM_SEL_SMT9_2 top]
[s]Ikebukuro[e]
[s]Roppongi[e]
[s]Underground Shopping Center[e]
[s]Ueno[e]

[sel BGM_SEL_SMT9_3 top]
[s]Shibuya[e]
[s]Shibuya 1009[e]



[sel BGM_SEL_SMT3 top]
[s]Large Map -Real World-[e]
[s]The Labyrinth of Amala[e]
[s]Large Map -Last Area-[e]
[s]Map -Real World-[e]

[sel BGM_SEL_SMT3_2 top]
[s]Luck[e]
[s]Shinjuku Hygiene Hospital[e]
[s]Warp Field[e]
[s]Map[e]

[sel BGM_SEL_SMT3_3 top]
[s]Shibuya[e]
[s]Ginza[e]
[s]Map -Last Area-[e]
[s]Tower of Kagutsuchi[e]

[sel BGM_SEL_SMT3_4 top]
[s]Ikebukuro[e]

[sel BGM_SEL_SMT2 top]
[s]Valhalla (3D)[e]
[s]Field (2D)[e]
[s]Center (3D)[e]
[s]Underground (3D)[e]

[sel BGM_SEL_SMT2_2 top]
[s]Disco[e]
[s]Makai (2D)[e]


[sel BGM_SEL_SMT1 top]
[s]Kichijoji[e]
[s]Arcade Street[e]
[s]Ginza[e]
[s]Shibuya[e]
