[msg THEURGY_USE1 [Takaya]]
[s][bup 17 165 0 1]Why.....?[n]Fate is supposed to have chosen me....[n][f 1 3 65535][w][e]
[s][bup 17 165 0 1]This again..... Is my resolve[n]not strong enough still?[n][f 1 3 65535][w][e]

[msg THEURGY_USE2 [Takaya]]
[s][bup 17 162 0 1]If so... I'll throw away my[n]trivial pride![n][f 1 3 65535][w][e]
[s][bup 17 162 0 1]With my entire being! I will[n]bring you to your knees![n][f 1 3 65535][w][e]
