[msg WASHOKU_HAIRU_ALSO [Menu]]
[s]"Seafood Full Course - 950 yen"[n][w][e]
[s]"Get smarter while you eat!"[n][w][e]

[sel RAMEN_SEL2 top]
[s]Prodigy Platter (680 yen)[e]
[s]Seafood Full Course (950 yen)[e]
[s]Cancel[e]

[msg WASHOKU_TUTO]
[s]You can increase your Academics here[n]by eating the various options.[n][w][e]

[msg WHATTOORDER]
[s]> What should you order.....[n][w][e]

[msg RAMEN_HAIRU_ALSO [Menu]]
[s]"Special Hagakure Bowl - 1100 yen"[n][w][e]
[s]"The collagen will make your skin[n]beautiful!"[n][w][e]

[sel RAMENREAL_SEL2 top]
[s]Pork (900 yen)[e]
[s]Special Hagakure Bowl (1100 yen)[e]
[s]Cancel[e]

[msg RAMEN_TUTO]
[s]You can increase your Charm by eating[n]various dishes here.[n][w][e]

[msg MANGA_SETUMEI]
[s]> Book On...[n][w][e]
[s]> There's a sign on the door.[n][w][e]
[s]> Undergoing renovations! Come back later.[n][w][e]

[msg MANGA_SETUMEI_N]
[s]> Book On...[n][w][e]
[s]> Looking through the window, you see[n]the shop in progress of renovations.[n][w][e]
[s]> The shop will be open at another time.[n][w][e]

[msg GYUDON_SETUMEI_N]
[s]> Beef Bowl Shop...[n][w][e]
[s]> The usual crowd has left as the[n]store is closed for the day....[n][w][e]

[msg KANMI_SETUMEI_N]
[s]> Sweet Shop...[n][w][e]
[s]> The sweet scent is still present[n]but slightly fainter...[n][w][e]
[s]> The store is closed for the day....[n][w][e]

[msg CrowdedAsUsual]
[s]> It's crowded as usual....[n][w][e]
[s]> You turn around to leave....[n][w][e]

[msg WAITUP [Distant Voice]]
[s]Wait![n][w][e]
[s][f 1 5] [n]> A voice calls your attention....[n][w][e]

[msg WAITER [Waiter]]
[s]Sorry about that....[n][w][e]
[s]I didn't realize someone of your caliber wanted[n]to dine here....[n][w][e]
[s]What can I get started for you?[n][w][e]

[msg CHARMU_GREAT]
[s]> It seems your charm caught the attention[n]of the staff![n][w][e]
[s]> You can now order take-out at the Beef[n]Bowl shop![n][w][e]

[msg CrowdedAsAlways]
[s]> It's crowded as always....[n][w][e]
[s]> Maybe if you were more charming you[n]could get their attention....[n][w][e]

[msg WELCOMEBACK [Waiter]]
[s]Welcome back![n][w][e]

[msg BEEF_BUY_OK [Waiter]]
[s]What would you like to buy?[n][w][e]

[msg COMEAGAIN [Waiter]]
[s]Come again![n][w][e]

[sel BEEF_SEL2 top]
[s]Umiushi Beef Bowl (200 yen) [e] 
[s]Great Yakiniku Bowl (1000 yen)[e] 
[s]Staunch Offai Bowl (1000 yen)[e] 
[s]Lithe Combo Bowl (1000 yen)[e] 
[s]Spring Cabbage Bowl (600 yen)[e] 
[s]Summer-Hot Bowl (1500 yen)[e] 
[s]Autumn Beef Bowl (800 yen)[e] 
[s]Winter Oden Bowl (1000 yen)[e] 
[s]Stamina Beef Bowl (1300 yen)[e] 
[s]Don't buy anything[e]

[msg BEEF_CANT_BUY [Waiter]]
[s]Your hands seem to be full of that[n]item.[n][w][e]
[s][f 1 5] [n]> You already have 99 of that item.[n][w][e]

[msg BEEF_MONEY_IN]
[s]> You handed them [f 2 4 9] yen.[n][w][e]

[msg BEEF_BUY_END]
[s]> Obtained [f 2 5 3 13 0].[n][w][e]

[msg BEEF_NO_MONEY]
[s]> You don't have enough money.[n][w][e]

[msg MAGICAL]
[s]One in 40k chance hit![n][w][e]
[s]Send a screenshot of this message to the mod[n]creator! Manga cafe functionality will be added![n][w][e]