
[msg BURGER_TUTO2]
[s]You can increase your social stats here[n]by trying the Big Eater Challenge.[n][w][e]

[sel BURGER_SEL2 top]
[s]Mystery Burger[e]
[s]Weekend Wilduck Set[e]
[s]Big Eater Challenge[e]
[s]Cancel[e]

[msg BURGER_HERO [Menu]]
[s]"Big Eater Challenge - 1200 yen"[n][w][e]
[s]"How the mighty fall to this challenge!"[n][w][e]
[s][f 1 5] [n]> You need a little bit of Courage to[n]eat here.[n][w][e]

[msg BURGER_TUTO]
[s]You can increase your Courage here by[n]trying the various items.[n][w][e]

[msg CANT_EAT_HERE ]
[s]> You don't feel confident in beating[n]this challenge...[n][w][e]
[s]> Maybe if you were more courageous[n]you could....[n]

[msg BURGER_HAIRU_ALSO [Menu]]
[s]"Weekend Wilduck Set - 700 yen"[n][w][e]
[s]"The ingredients are unique!!"[n][w][e]
[s][f 1 5] [n]> You need a little bit of Courage to[n]eat here.[n][w][e]

[msg WHATTOORDER]
[s]> What should you order.....[n][w][e]

[msg SCR_MSG_HURUHON_NG_NT]
[s]> Bookworms Used Books...[n][w][e]
[s]> The store is closed right now.[n][w][e]

[msg OCTOPI_OPEN_NAH]
[s]> Octopia...[n][w][e]
[s]> The shutter is open, but no one is[n]inside.[n][w][e]
[s]> You remind the mod creator to fix[n]the textures eventually....[n][w][e]
