[msg MSG_TARTAROS_BTL_YUKARI_ [Yukari Takeba]]
[s][bup 2 201 0 0]If you're not gonna move, then we'll make you![n][w][e]

[msg MSG_TARTAROS_BTL_YUKARI__2 [Yukari Takeba]]
[s][bup 2 201 0 0]Ready? Let's go![n][w][e]

[msg MSG_TARTAROS_BTL_JUNPEI_ [Junpei Iori]]
[s][bup 5 201 0 0]Move out, squad! Keep your eyes on me![n][w][e]

[msg MSG_TARTAROS_BTL_JUNPEI__2 [Junpei Iori]]
[s][bup 5 201 0 0]Looks tougher than I thought... But ain't nothin' stoppin' me![n][w][e]

[msg MSG_TARTAROS_BTL_SANADA_ [Akihiko Sanada]]
[s][bup 7 201 0 0]Sorry, but we're breaking through![n][w][e]

[msg MSG_TARTAROS_BTL_SANADA__2 [Akihiko Sanada]]
[s][bup 7 201 0 0]This'll be fun. C'mon, let's move![n][w][e]

[msg MSG_TARTAROS_BTL_MITSURU [Mitsuru Kirijo]]
[s][bup 4 201 0 0]Incoming! Brace yourselves![n][w][e]

[msg MSG_TARTAROS_BTL_MITSURU_2 [Mitsuru Kirijo]]
[s][bup 4 201 0 0]Let's get through this![n][w][e]

[msg MSG_TARTAROS_BTL_MITSURU_3 [Mitsuru Kirijo]]
[s]I'll leave this to you![n][w][e]

[msg MSG_TARTAR_BTL_PT_MITSUR [Mitsuru Kirijo]]
[s]Stay alert! The enemy's powers are unknown![n][w][e]

[msg MSG_TARTAR_BTL_PT_MITSUR_2 [Mitsuru Kirijo]]
[s][bup 4 201 0 0]Are you ready? We're forcing our way through![n][w][e]

[msg MSG_TARTAROS_BTL_AEGIS_0 [Aigis]]
[s][bup 3 201 0 0]Approaching enemy Shadow. Eliminating target.[n][w][e]

[msg MSG_TARTAROS_BTL_AEGIS_1 [Aigis]]
[s][bup 3 201 0 0]Entering combat. Come and get it, as they say.[n][w][e]

[msg MSG_TARTAROS_BTL_AEGIS_2 [Aigis]]
[s][bup 3 201 0 0]This may be a tough battle. Let's exercise caution![n][w][e]

[msg MSG_TARTAROS_BTL_AEGIS_3 [Aigis]]
[s][bup 3 201 0 0]I'll give it everything I've got, so let's work together![n][w][e]

[msg MSG_TARTAROS_BTL_KOROMAR [Koromaru]]
[s][bup 10 201 0 0]Grrr... Arf![n][w][e]

[msg MSG_TARTAROS_BTL_KOROMAR_2 [Koromaru]]
[s][bup 10 201 0 0]Grrrrrr...![n][w][e]

[msg MSG_TARTAROS_BTL_AMADA_0 [Ken Amada]]
[s][bup 8 201 0 0]Come on, bring it! I'll take you on![n][w][e]

[msg MSG_TARTAROS_BTL_AMADA_1 [Ken Amada]]
[s][bup 8 201 0 0]Here it comes! Let's take it down![n][w][e]

[msg MSG_TARTAROS_BTL_ARAGAKI [Shinjiro Aragaki]]
[s][bup 9 201 0 0]Get ready, here it comes![n][w][e]

[msg MSG_TARTAROS_BTL_ARAGAKI_2 [Shinjiro Aragaki]]
[s][bup 9 201 0 0]If we can't get through, then we're just gonna have to pulverize 'em.[n][w][e]

[msg MSG_TARTAROS_BTL_FUKA_1 [Fuuka Yamagishi]]
[s]Incoming enemy Shadow![n][w][e]

[msg MSG_TARTAROS_BTL_FUKA_2 [Fuuka Yamagishi]]
[s]I'll support you! We'll get through this together![n][w][e]

[msg MSG_TARTAROS_BTL_FUKA_3 [Fuuka Yamagishi]]
[s]You can do this! I believe in you![n][w][e]
